name: CI

on:
  push:
    branches: ['main']

jobs:
  build-mingw:
    strategy:
      matrix:
        arch: [x86, x64]
        sys: [mingw32, mingw64]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          install: >-
            base-devel
            mingw-w64-${{ matrix.sys }}-gcc
            git
            make

      - name: Build Binary
        shell: msys2 {0}
        run: "./build/${{ matrix.arch }}.mingw.sh"

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.sys }}-${{ matrix.arch }}
          path: bin/

  publish:
    needs: [build-mingw]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: download
          merge-multiple: true

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: full-dump
          path: download
