name: Opus Worker CI

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { arch: x64, sys: MINGW64, prefix: mingw64, carch: x86_64 }
          - { arch: x86, sys: MINGW32, prefix: mingw32, carch: i686 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: xiph/opus
          submodules: 'true'

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}

      -  name: Install deps
         run: msys2 -c 'pacman -S --noconfirm --needed autoconf automake libtool pkgconf mingw-w64-x86_64-gcc mingw-w64-x86_64-pkg-config make mingw-w64-x86_64-libogg tree i686-w64-mingw32-gcc i686-w64-mingw32-pkg-config'
        
      - run: ls

      - name: Autogen configure file
        run: |
          set MSYSTEM=${{ matrix.sys }}
          msys2 -c './autogen.sh'
      
      - run: ls

      - name: Build Binary
        run: |
          set MSYSTEM=${{ matrix.sys }}
          msys2 -c './configure --host=${{ matrix.carch }}-w64-mingw32 --prefix=/${{ matrix.prefix }} --disable-static --enable-shared && make'

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opus-${{ matrix.sys }}-${{ matrix.carch }}
          path: bin/